import type { Metadata } from "next";
import { Inter, Lora } from "next/font/google";
import { NextUIProvider } from "@nextui-org/react";

import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: '--font-inter', display: 'swap', });

const lora = Lora({
  subsets: ['latin'], variable: '--font-lora', display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${lora.variable}`}>
      <body >
        <NextUIProvider>{children}</NextUIProvider>
      </body>
    </html>
  );
}
